name: Weekly Job Tracker

on:
  schedule:
    # 05:20 UTC is 10:50 AM IST (Sunday)
    - cron: '20 5 * * 0'
  workflow_dispatch: 

jobs:
  run-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Scraping Tools
        run: pip install requests beautifulsoup4

      - name: Run Script
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: python tracker.py